### ISSUE TITLE
Чел, не пиши пж такие комменты

### ISSUE THREAD

**Issue by Laynexx-ns** [heenimm/srvrClct#1]
У тебя полностью нерабочая инструкция по запуску + страшный ридми
Ну и кста. Если ты уберешь комменты в application.go и поменяешь названия переменных, то все равно видно, что код скопирован))

**Comment by heenimm** [comment]
Сильно поспорю... данный редми протестирован, все запускается и сервер работает. Могу видео прислать. Коммент остался старый, когда эндпоинт менялся, но это не критично для работы  программы. А также не вижу никаких предпосылок  говорить о копировании текста по названию переменных, так как они стандартные для веб - серверов! За каждое предложение в файле application.go могу легко разъяснить!
